name: Generate Snake 🐍

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true   # future-safe

    steps:
      # 🔄 Generate Snake Animations
      - name: Generate Snake Animations 🎨
        uses: Platane/snk@v3
        with:
          github_user_name: Pranjul2121
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake-blue.svg?color_snake=#00bfff&color_dots=#e6f7ff,#bae7ff,#91d5ff,#69c0ff,#40a9ff
            dist/github-snake-orange.svg?color_snake=orange&color_dots=#fff7e6,#ffd591,#ffa940,#fa8c16,#d46b08
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # 🚀 Deploy to output branch
      - name: Deploy to output branch 🚀
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          commit_message: "🐍 Update Snake Animation"
          keep_history: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
